//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinWatch
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class COINS_FOLLOWED_PRICES
    {
        public int COIN_ID { get; set; }
        public string COIN_NAME { get; set; }
        public Nullable<decimal> COIN_VALUE { get; set; }
    }
}
