//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinWatch
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class FOLLOWING_POSTS
    {
        public int LOGGED_IN_USER { get; set; }
        public int FOLLOWED_USER { get; set; }
        public string USERNAME { get; set; }
        public string POST { get; set; }
        public string COIN_NAME { get; set; }
    }
}
