//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinWatch
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class LIKED_OBJECT_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIKED_OBJECT_TYPE()
        {
            this.LIKE_DISLIKE = new ObservableCollection<LIKE_DISLIKE>();
        }
    
        public int LIKED_OBJECT_TYPE_ID { get; set; }
        public string LIKED_OBJECT_TYPE1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<LIKE_DISLIKE> LIKE_DISLIKE { get; set; }
    }
}
