//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinWatch
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class NOTIFICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTIFICATION()
        {
            this.NOTIFIED_USER = new ObservableCollection<NOTIFIED_USER>();
            this.NOTIFIED_USER1 = new ObservableCollection<NOTIFIED_USER>();
        }
    
        public int NOTIFICATION_ID { get; set; }
        public int NOTIFICATION_TYPE_ID { get; set; }
        public Nullable<int> COIN_ID { get; set; }
        public Nullable<int> COMMENT_ID { get; set; }
        public Nullable<int> LIKE_ID { get; set; }
        public Nullable<int> FOLLOWER_ID { get; set; }
        public Nullable<int> POST_ID { get; set; }
        public System.DateTime DATETIME { get; set; }
    
        public virtual COIN COIN { get; set; }
        public virtual COMMENT COMMENT { get; set; }
        public virtual LIKE_DISLIKE LIKE_DISLIKE { get; set; }
        public virtual POST POST { get; set; }
        public virtual NOTIFICATION_TYPE NOTIFICATION_TYPE { get; set; }
        public virtual USERT USERT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<NOTIFIED_USER> NOTIFIED_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<NOTIFIED_USER> NOTIFIED_USER1 { get; set; }
    }
}
