//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinWatch
{
    using System;
    using System.Collections.ObjectModel;
    
    
    public partial class POST 
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POST()
        {
            this.COMMENTs = new ObservableCollection<COMMENT>();
            this.LIKE_DISLIKE = new ObservableCollection<LIKE_DISLIKE>();
            this.NOTIFICATIONs = new ObservableCollection<NOTIFICATION>();
        }
    
        public int POST_ID { get; set; }
        public int USER_ID { get; set; }
        public int COIN_ID { get; set; }
        public string MESSAGE { get; set; }
        public System.DateTime DATETIME { get; set; }
    
        public virtual COIN COIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<COMMENT> COMMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<LIKE_DISLIKE> LIKE_DISLIKE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<NOTIFICATION> NOTIFICATIONs { get; set; }
        public virtual USERT USERT { get; set; }
    }
}
