//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinWatch
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class USERT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERT()
        {
            this.COIN_FOLLOW = new ObservableCollection<COIN_FOLLOW>();
            this.COMMENTs = new ObservableCollection<COMMENT>();
            this.INVALID_LOGIN = new ObservableCollection<INVALID_LOGIN>();
            this.LIKE_DISLIKE = new ObservableCollection<LIKE_DISLIKE>();
            this.NOTIFICATIONs = new ObservableCollection<NOTIFICATION>();
            this.NOTIFIED_USER = new ObservableCollection<NOTIFIED_USER>();
            this.POSTs = new ObservableCollection<POST>();
            this.VALID_LOGIN = new ObservableCollection<VALID_LOGIN>();
            this.WALLET_LIST = new ObservableCollection<WALLET_LIST>();
            this.USERT1 = new ObservableCollection<USERT>();
            this.USERTs = new ObservableCollection<USERT>();
            this.NOTIFIED_USER1 = new ObservableCollection<NOTIFIED_USER>();
        }
    
        public int USER_ID { get; set; }
        public string USERNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string SURNAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PASSWORD { get; set; }
        public string ABOUTME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<COIN_FOLLOW> COIN_FOLLOW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<COMMENT> COMMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<INVALID_LOGIN> INVALID_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<LIKE_DISLIKE> LIKE_DISLIKE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<NOTIFICATION> NOTIFICATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<NOTIFIED_USER> NOTIFIED_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<POST> POSTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<VALID_LOGIN> VALID_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<WALLET_LIST> WALLET_LIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<USERT> USERT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<USERT> USERTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<NOTIFIED_USER> NOTIFIED_USER1 { get; set; }
    }
}
