//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinWatch
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class USER_COMMENT_LIKES
    {
        public int COMMENT_ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string COMMENT { get; set; }
        public string PERSON_WHO_LIKED { get; set; }
        public string TYPE { get; set; }
    }
}
