//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinWatch
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class VALID_LOGIN
    {
        public long SESSION_ID { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime LOGIN_DATE { get; set; }
    
        public virtual USERT USERT { get; set; }
    }
}
