//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinWatch
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class WALLET
    {
        public short WALLET_ID { get; set; }
        public Nullable<int> COIN_ID { get; set; }
        public string COIN_ADDRESS { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
    
        public virtual COIN COIN { get; set; }
        public virtual WALLET_LIST WALLET_LIST { get; set; }
    }
}
