//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinWatch
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class WALLET_LIST
    {
        public short WALLET_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
    
        public virtual USERT USERT { get; set; }
        public virtual WALLET WALLET { get; set; }
    }
}
